/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(home)/': RouteRecordInfo<
      '/(home)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/query/': RouteRecordInfo<
      '/(home)/query/',
      '/query',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/query/[id]': RouteRecordInfo<
      '/(home)/query/[id]',
      '/query/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(home)/routes/': RouteRecordInfo<
      '/(home)/routes/',
      '/routes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/routes/[slug]': RouteRecordInfo<
      '/(home)/routes/[slug]',
      '/routes/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/(home)/scroll-cache/': RouteRecordInfo<
      '/(home)/scroll-cache/',
      '/scroll-cache',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/scroll-cache/[id]': RouteRecordInfo<
      '/(home)/scroll-cache/[id]',
      '/scroll-cache/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/docs/': RouteRecordInfo<
      '/docs/',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tools/': RouteRecordInfo<
      '/tools/',
      '/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/(home)/index.vue': {
      routes:
        | '/(home)/'
      views:
        | never
    }
    'src/views/(home)/query/index.vue': {
      routes:
        | '/(home)/query/'
      views:
        | never
    }
    'src/views/(home)/query/[id].vue': {
      routes:
        | '/(home)/query/[id]'
      views:
        | never
    }
    'src/views/(home)/routes/index.vue': {
      routes:
        | '/(home)/routes/'
      views:
        | never
    }
    'src/views/(home)/routes/[slug].vue': {
      routes:
        | '/(home)/routes/[slug]'
      views:
        | never
    }
    'src/views/(home)/scroll-cache/index.vue': {
      routes:
        | '/(home)/scroll-cache/'
      views:
        | never
    }
    'src/views/(home)/scroll-cache/[id].vue': {
      routes:
        | '/(home)/scroll-cache/[id]'
      views:
        | never
    }
    'src/views/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/views/docs/index.vue': {
      routes:
        | '/docs/'
      views:
        | never
    }
    'src/views/tools/index.vue': {
      routes:
        | '/tools/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
